import pymysql

db = pymysql.connect(
    host='localhost',
    user='root',
    password='ff2017',
    charset='utf8',
    database='tedi_data'
)


def create_database():
    cur = db.cursor()
    cur.execute('''
    CREATE TABLE PERSON_INFO (
    USER_ID BIGINT ( 20 ) PRIMARY KEY NOT NULL,
    OPEN_ID VARCHAR ( 64 ),
    GENDER VARCHAR ( 2 ),
    NATION VARCHAR ( 20 ),
    AGE INT, 
    BIRTHDAY VARCHAR ( 20 ),
    CREATE_TIME TIMESTAMP )''')
    cur.execute('''
    CREATE TABLE VENUE_INFO(
    GRID_POINT_ID BIGINT(20) PRIMARY KEY NOT NULL,
    NAME VARCHAR(255),
    POINT_TYPE VARCHAR(50),
    X_COR DECIMAL(12,2),
    Y_COR DECIMAL(12,2),
    CREATE_TIME TIMESTAMP)
    ''')
    cur.execute('''
    CREATE TABLE PERSONAL_REPORT_INFO(
    SNO BIGINT(20) PRIMARY KEY NOT NULL,
    USER_ID BIGINT(20) NOT NULL,
    X_COR DECIMAL(12, 2),
    Y_COR DECIMAL(12, 2),
    SYMPTOM VARCHAR(100), 
    NA_RESULT VARCHAR(10),
    RES_FLAG INT, 
    DUMP_TIME TIMESTAMP,
    FOREIGN KEY (USER_ID) REFERENCES PERSON_INFO(USER_ID) ON DELETE SET DEFAULT 
    )''')
    cur.execute('''
    CREATE TABLE VENUE_CODE_INFO(
    SNO BIGINT(20) PRIMARY KEY NOT NULL,
    GRID_POINT_ID BIGINT(20),
    USER_ID BIGINT(20),
    TEMPERATURE DOUBLE,
    CREATE_TIME TIMESTAMP,
    FOREIGN KEY (GRID_POINT_ID) REFERENCES VENUE_INFO(GRID_POINT_ID) ON DELETE SET DEFAULT,
    FOREIGN KEY (USER_ID) REFERENCES PERSON_INFO(USER_ID) ON DELETE SET DEFAULT 
    )''')
    cur.execute('''
    CREATE TABLE NA_SAMPLE_INFO(
    SNO BIGINT(20) PRIMARY KEY NOT NULL,
    USER_ID BIGINT(20),
    CYSJ TIMESTAMP,
    JCSJ TIMESTAMP,
    JG VARCHAR(50),
    GRID_POINT_ID BIGINT(20),
    FOREIGN KEY (USER_ID) REFERENCES PERSON_INFO(USER_ID) ON DELETE SET DEFAULT ,
    FOREIGN KEY (GRID_POINT_ID) REFERENCES VENUE_INFO(GRID_POINT_ID) ON DELETE SET DEFAULT)
    ''')
    cur.execute('''
    CREATE TABLE VACCINATION_INFO(
    SNO BIGINT(20) PRIMARY KEY NOT NULL,
    INJECT_SN VARCHAR(50) NOT NULL,
    USER_ID BIGINT(20) NOT NULL,
    AGE INT,
    GENDER VARCHAR(10),
    BIRTHDATE VARCHAR(50), 
    INJECT_DATE TIMESTAMP,
    INJECT_TIMES VARCHAR(30),
    VACCINE_TYPE VARCHAR(30),
    FOREIGN KEY (USER_ID) REFERENCES PERSON_INFO(USER_ID) ON DELETE SET DEFAULT 
    )''')
    cur.execute('''
        CREATE TABLE po_user(
        uid BIGINT(20) PRIMARY KEY NOT NULL
        )''')


def main():
    create_database()


if __name__ == '__main__':
    main()
    db.close()
